import Wish from './WishList';
import CategoriesList from './Categories';
import CartList from './Cart';
import HomeScreen from './Home';
import  AccountScreen from './Account';
import ContactScreen from './Account/Contact';
export const WishList = Wish;
export const Home =HomeScreen; 
export const Categories = CategoriesList;
export const Cart = CartList;
export const Account=AccountScreen;
export const Contact=ContactScreen;