import LocalizedStrings from 'react-native-localization';
const Languages = {
    en: {
      //On Boarding
      Title1:'Relaxed',
      Title2:'Playfull',
      Title3:'Excentric',
      Title4:'Funcky',
      Subtitle1:'Here it first wear it first',
      Subtitle2:'Look Good Feel Good',
      Subtitle3:'Your Style Your Way',
      Subtitle4:'Find Your Outfits',
      Description1: 'Create basic to complex profiles for your sport or career',
      Description2: 'Create basic to complex profiles for your sport or career',
      Description3: 'Create basic to complex profiles for your sport or career',
      Description4: 'Create basic to complex profiles for your sport or career',
      LetsStart:"Let's get started",
      StartedDescription:"Login to your account below or signup for an amazing experiance",
      HaveAccount:"Have an acount? Login",
      JoinUs:"Join us it's free",
      CheckInGuest:"Checkin as guest",
      Next:"Next",
      RememberMe:"Remember Me",
      ForgotPassword:"Forgot Password?",
      ForgotPasswordDescription:"Enter the email address associate with your account",
      ResetPassword:"Reset password",
      Welcome:'Welcome back',
      CreateAccount:'Create Account',
      WelcomeDescription:'Use your credential below to logged with your account',
      CreateAccountDescription:`Let's us know your detail to register with Uae Sell`,
      Email:"Email",
      Password:"Password",
      HaveAccountSignup:"Don't have an account?",
      HaveAccountLogin:"Already have an account?",
      IncorrectPassword:'Incorrect password',
      //    
      Exit: "Exit",
      ExitConfirm: "Are you sure you want to exit this app",
      YES: "YES",
      OK: "OK",
      ViewMyOrders: "View My Oders",
      CANCEL: "CANCEL",
      Confirm: "Confirm",
  
      // Scene's Titles
      Home: "Home",
      Intro: "Intro",
      Product: "Product",
      Cart: "Cart",
      WishList: "WishList",
  
      // Home
      products: "products",
  
      // TopBarz
      ShowFilter: "Sub Categories",
      HideFilter: "Hide",
      Sort: "Sort",
      textFilter: "Recent",
  
      // Category
      ThereIsNoMore: "There is no more product to show",
  
      // Product
      AddtoCart: "Add to Cart",
      AddtoWishlist: "Add to Wishlist",
      ProductVariations: "Variations",
      NoVariation: "This product don't have any variation",
      AdditionalInformation: "Description",
      NoProductDescription: "No Product Description",
      ProductReviews: "Reviews",
      NoReview: "This product don't have any reviews ...yet",
      BUYNOW: "BUY NOW",
      OutOfStock: "OUT OF STOCK",
      ProductLimitWaring: "You can't add more than 10 product",
      EmptyProductAttribute: "This product don't have any attributes",
      ProductFeatures: "Features",
      ErrorMessageRequest: "Can't get data from server",
      NoConnection: "No internet connection",
      ProductRelated: "Related Products",
  
      // Cart
      NoCartItem: "There is no product in cart",
      Total: "Total",
      EmptyCheckout: "Sorry, you can't check out an empty cart",
      RemoveCartItemConfirm: "Remove this product from cart?",
      MyCart: "Cart",
      Order: "Order",
      ShoppingCart: "Shopping Cart",
      ShoppingCartIsEmpty: "Your Cart is Empty",
      AddProductToCart: "Add a product to the shopping cart",
      TotalPrice: "Total Price:",
      YourDeliveryInfo: "Your Shipping Detail",
      ShopNow: "Shop Now",
      YourChoice: "Your cart:",
      YourSale: "Your Sale:",
      SubtotalPrice: "Subtotal Price:",
      BuyNow: "Buy Now",
      Items: "items",
      Item: "item",
      ThankYou: "Thank you",
      FinishOrderCOD: "You can use to number of order to track shipping status",
      FinishOrder:
        "Thank you so much for your purchased, to check your delivery status please go to My Orders",
      NextStep: "Next Step",
      ConfirmOrder: "Confirm Order",
      RequireEnterAllFileds: "Please enter all fields",
      InvalidFieldsEntered:'Invalid field(s) entered',
      Error: "Error",
      InvalidEmail: "Invalid email address",
      Finish: "Finish",
  
      // Wishlist
      NoWishListItem: "There is no item in wishlist",
      MoveAllToCart: "Add all to cart",
      EmptyWishList: "Empty wishlist",
      EmptyAddToCart: "Sorry, the wishlist is empty",
      RemoveWishListItemConfirm: "Remove this product from wishlist?",
      CleanAll: "Clean All",
  
      // Sidemenu
      SignIn: "Log In",
      SignOut: "Log Out",
      GuestAccount: "Guest Account",
      CantReactEmailError:
        "We can't reach your email address, please try other login method",
      NoEmailError: "Your account don't have valid email address",
      EmailIsNotVerifiedError:
        "Your email address is not verified, we can' trust you",
      Login: "Log into your account",
      Logout: "Logout",
      Shop: "Home",
      Category: "Category",
  
      // Checkout
      Checkout: "Checkout",
      ProceedPayment: "Proceed Payment",
      Purchase: "Purchase",
      CashOnDelivery: "Cash on Delivery",
      CreditCard: "Credit Card",
      PaymentMethod: "Payment Method - Not select",
      PaymentMethodError: "Please select your payment method",
      PayWithCoD: "Your purchase will be pay when goods were delivered",
      PayWithPayPal: "Your purchase will be pay with PayPal",
      Paypal: "paypal",
      Stripe: "stripe",
      PayWithStripe: "Your purchase will be pay with Stripe",
      ApplyCoupon: "Apply",
      CouponPlaceholder: "Coupon Code",
      Apply: "Apply",
      Applying: "Applying",
      Back: "Back",
      CardNamePlaceholder: "Name written on card",
      BackToHome: "Back to Home",
      OrderCompleted: "Your order was completed",
      OrderCanceled: "Your order was canceled",
      OrderFailed: "Something went wrong...",
      OrderCompletedDesc: "Your order id is ",
      OrderCanceledDesc:
        "You have canceled the order. The transaction has not been completed",
      OrderFailedDesc:
        "We have encountered an error while processing your order. The transaction has not been completed. Please try again",
      OrderTip:
        'Tip: You could track your order status in "My Orders" section from side menu',
      Delivery: "Delivery",
      Payment: "Payment",
      Complete: "Complete",
      EnterYourFirstName: "Enter your First Name",
      EnterYourLastName: "Enter your Last Name",
      EnterYourEmail: "Enter your email",
      EnterYourPhone: "Enter your phone",
      EnterYourAddress: "Enter your address",
      CreateOrderError: "Cannot create new order. Please try again later",
  
      // myorder
      OrderId: "Order ID",
      MyOrder: "My Order",
      NoOrder: "You don't have any orders",
      OrderDate: "Order Date: ",
      OrderStatus: "Status: ",
      OrderPayment: "Payment method: ",
      OrderTotal: "Total: ",
      OrderDetails: "Show detail",
      OrderLineItems: "Line Items: ",
      ShippingAddress: "Shipping Address:",
      Refund: "Refund",
  
      News: "News",
      PostDetails: "Post Details",
      FeatureArticles: "Feature articles",
      MostViews: "Most views",
      EditorChoice: "Editor choice",
  
      // settings
      Settings: "Settings",
      BASICSETTINGS: "BASIC SETTINGS",
      Language: "Language",
      INFO: "INFO",
      About: "About us",
  
      // language
      AvailableLanguages: "Available Languages",
      SwitchLanguage: "Switch Language",
      SwitchLanguageConfirm: "Switch language require an app reload, continue?",
  
      // about us
      AppName: "MSTORE",
      AppDescription: "React Native template for mCommerce",
      AppContact: " Contact us at: mstore.io",
      AppEmail: " Email: support@mstore.io",
      AppCopyRights: "© MSTORE 2016",
  
      // contact us
      contactus: "Contact Us",
  
      // form
      NotSelected: "Not selected",
      EmptyError: "This field is empty",
      DeliveryInfo: "Delivery Info",
      FirstName: "First Name",
      LastName: "Last Name",
      Address: "Address",
      City: "Town/City",
      State: "State",
      NotSelectedError: "Please choose one",
      Postcode: "Postcode",
      Country: "Country",
      Email: "Email",
      Phone: "Phone Number",
      Note: "Note",
  
      // search
      Search: "Search",
      SearchPlaceHolder: "Search product by name",
      NoResultError: "Your search keyword did not match any products.",
      Details: "Details",
  
      // filter panel
      Categories: "Categories",
      Loading: "LOADING...",
      welcomeBack: "Welcome back! ",
      seeAll: "Show All",
  
      // Layout
      cardView: "Card ",
      simpleView: "List View",
      twoColumnView: "Two Column ",
      threeColumnView: "Three Column ",
      listView: "List View",
      default: "Default",
      advanceView: "Advance ",
      horizontal: "Horizontal ",
  
      couponCodeIsExpired: "This coupon code is expired",
      invalidCouponCode: "This coupon code is invalid",
      remove: "Remove",
      applyCouponSuccess: "Congratulations! Coupon code applied successfully ",
      reload: "Reload",
  
      ShippingType: "Shipping method",
  
      // Place holder
      TypeFirstName: "Type your first name",
      TypeLastName: "Type your last name",
      TypeAddress: "Type address",
      TypeCity: "Type your town or city",
      TypeState: "Type your state",
      TypeNotSelectedError: "Please choose one",
      TypePostcode: "Type postcode",
      TypeEmail: "Type email (Ex. acb@gmail.com)",
      TypePhone: "Ex. (99) 9999-9999",
      TypeNote: "Note",
      TypeCountry: "Select country",
      SelectPayment: "Select Payment method",
      close: "CLOSE",
      noConnection: "NO INTERNET ACCESS",
  
      // user profile screen
      AccountInformations: "Account Informations",
      PushNotification: "Push notification",
      DarkTheme: "Dark Theme",
      Privacy: "Privacy policy",
      SelectCurrency: "Select currency",
      Name: "Name",
      Gender:'Gender',
      SelectAGender:'Please select a gender',
      Currency: "Currency",
      Languages: "Languages",
      Guest: "Guest",
      FacebookLogin: "Facebook Login",
      Or: "Or",
      UserOrEmail: "Email",
      DontHaveAccount: "Don't have account? ",
      accountDetails: "Account Details",
      username: "Username",
      email: "Email",
      generatePass: "Use generate password",
      password: "Password",
      signup: "Sign Up",
      profileDetail: "Profile Details",
      firstName: "First name",
      lastName: "Last name",
  
      // Horizontal
      featureProducts: "Feature Products",
      bagsCollections: "Gears Collections",
      womanCollections: "Woman Collections",
      manCollections: "Man Collections",
      jacket: 'Jacket',
      hoodies: "Hoodies & Sweatshirts",
      promotion: "Promotions",
      newArrivals: "New Arrivals",
      shopByCategory: "Shop By Category",
  
  
      // Modal
      Select: "Select",
      Cancel: "Cancel",
  
      LanguageName: "English",
  
      // review
      vendorTitle: "Vendor",
      comment: "Leave a review",
      yourcomment: "Your comment",
      placeComment:
        "Tell something about your experience or leave a tip for others",
      writeReview: "Review",
      thanksForReview:
        "Thanks for the review, your content will be verify by the admin and will be published later",
      errInputComment: "Please input your content to submit",
      errRatingComment: "Please rating to submit",
      send: "Send",
      termCondition: "Term & Condition",
      Subtotal: "Subtotal",
      Discount: "Discount",
      Shipping: "Shipping",
      Recents: "Recents",
      Filters: "Filters",
      Pricing: "Pricing",
      Filter: "Filter",
      ClearFilter: "Clear Filter",
      ProductCatalog: "Product Catalog",
      ProductTags: "Product Tags",
      AddToAddress: "Add to Address",
      GoogleLogin: "Google Login",
      FAQTopics: "FAQ Topics",
      FAQ: "FAQ",
      ContactInformation: "Contact Information",
      Comment: "Comment",
      Submit: "Submit",
      Location: "Store Location",
      Free: "Free",
      Days: "Days",
      NoShippingMsg: "Don't have any shipping methods for your address"
    },
    ar: {
        //On Boarding
      Title1:'استرخاء',
      Title2:'لعبة',
      Title3:'غريب الأطوار',
      Title4:'غير تقليدي',
      Subtitle1:'هنا هو أولا يلبسه أولا',
      Subtitle2:'يبدو جيدا',
      Subtitle3:'أسلوبك طريقك',
      Subtitle4:'اعثروا على ملابسكم',
      Description1: 'إنشاء أساسي إلى معقد ملفات لرياضتك أو مهنتك',
      Description2: 'إنشاء أساسي إلى معقد ملفات لرياضتك أو مهنتك',
      Description3: 'إنشاء أساسي إلى معقد ملفات لرياضتك أو مهنتك',
      Description4: 'إنشاء أساسي إلى معقد ملفات لرياضتك أو مهنتك',
      LetsStart:"لنبدأ",
      StartedDescription:"أدخل إلى حسابك بالأسفل أو سجل لتجربة مذهلة",
      HaveAccount:"هل لديك حساب ؟ الولوج",
      JoinUs:"إنضم إلينا إنه مجاني",
      CheckInGuest:"تحقق كضيف",
      Next:"التالي",
      RememberMe:"تذكرنى",
      ForgotPassword:"هل نسيت كلمة المرور",
      ForgotPasswordDescription:"أدخل عنوان البريد الإلكتروني المرتبط بحسابك",
      ResetPassword:"إعادة تعيين كلمة المرور",
      Welcome:'مرحبا بعودتك',
      CreateAccount:'إنشاء حساب',
      WelcomeDescription:'استخدم بيانات الاعتماد الخاصة بك أدناه لتسجيل الدخول إلى حسابك',
      CreateAccountDescription:`دعنا نعرف التفاصيل الخاصة بك للتسجيل في بيع الإمارات`,
      Email:"البريد الإلكتروني",
      Password:"كلمه السر",
      HaveAccountSignup:"لا تملك حساب؟",
      HaveAccountLogin:"هل لديك حساب؟",
      IncorrectPassword:'كلمة سر خاطئة',
      // 
      Exit: "خروج",
      ExitConfirm: "هل تود الخروج من التطبيق",
      YES: "نعم",
      OK: "نعم",
      ViewMyOrders: "أستعرض طلبي",
      CANCEL: "إلغاء",
      Confirm: "تأكيد",
  
      // Scene's Titles
      Home: "الرئيسة",
      Intro: "مقدمة",
      Product: "منتج",
      Cart: "عربة التسوق",
      WishList: "الرغبات",
  
      // Home
      products: "منتجات",
  
      // TopBar
      ShowFilter: "الفئات الفرعية",
      HideFilter: "إخفاء",
      Sort: "فرز",
      textFilter: "الأخيرة",
  
      // Category
      ThereIsNoMore: "لا يوجد منتجات لإظهارها",
  
      // Product
      AddtoCart: "أضف إلى السلة",
      AddtoWishlist: "أضف إلى قائمة الرغبات",
      ProductVariations: "الاختلافات",
      NoVariation: "هذا المنتج ليس لديهم أي اختلاف",
      AdditionalInformation: "معلومات",
      NoProductDescription: "لا يوجد وصف",
      ProductReviews: "التعليقات",
      NoReview: "لا توجد مراجعات لهذا المنتج",
      BUYNOW: "اشتر الآن",
      ProductLimitWaring: "لا يمكن اضافة اكثر من هذا العدد",
      EmptyProductAttribute: "لم يتم اضافة اي صفات لهذا المنتج",
      ProductFeatures: "المميزات",
      ErrorMessageRequest: "لا يمكن الحصول على البيانات من الخادم",
      NoConnection: "انت غير متصل بالإنترنت",
      ProductRelated: "ربما يعجبك أيضا",
      // Cart
      NoCartItem: "لا يوجد منتجات في العربة",
      Total: "مجموع",
      EmptyCheckout: "عذراً، لا يمكن الاستمرار مع عربة فارغة",
      RemoveCartItemConfirm: "إزالة هذا المنتج من سلة المشتريات؟",
      MyCart: "عربة التسوق",
      Order: "طلب",
      ShoppingCart: "عربة التسوق",
      ShoppingCartIsEmpty: "عربة التسوق فارغة",
      Delivery: "التوصيل",
      AddProductToCart: "إضافة منتج إلى عربة التسوق",
      TotalPrice: "السعر الكلي:",
      YourDeliveryInfo: "معلومات الإستلام:",
      ShopNow: "تسوق الآن",
      YourChoice: "عربتك:",
      YourSale: "مبيعاتك:",
      SubtotalPrice: "السعر الإجمالي:",
      BuyNow: "اشتر الآن",
      Items: "العناصر",
      Item: "عنصر",
      ThankYou: "شكراً لك",
      FinishOrderCOD: "يمكنك استخدام هذا الرقم لتتبع شحنتك",
      FinishOrder:
        "شكراً لإتمام عملية الشراء, للتحقق من حالة الطلب الرجاء مراجعة طلباتي",
      NextStep: "الخطوة التالية",
      ConfirmOrder: "أكد الطلب",
      RequireEnterAllFileds: "الرجاء إدخال جميع الحقول",
      Error: "خطأ",
      InvalidEmail: "البريد الإلكتروني غير صحيح",
      InvalidFieldsEntered:'تم إدخال حقل (حقول) غير صالحة',
      Finish: "إنهاء",
  
      // Wishlist
      NoWishListItem: "لا يوجد منتجات في قائمة الرغبات",
      MoveAllToCart: "اضف الكل للسلة",
      EmptyWishList: "القائمة فارغة",
      EmptyAddToCart: "عذرا، قائمة الرغبات فارغة",
      RemoveWishListItemConfirm: "إزالة هذا المنتج من قائمة الرغبات؟",
      CleanAll: "ازالة الكل",
  
      // Sidemenu
      SignIn: "تسجيل الدخول",
      SignOut: "خروج",
      GuestAccount: "زائر",
      CantReactEmailError: "هذا البريد غير موجود، جرب طريقة تسجيل دخول أخرى",
      NoEmailError: "البريد الإلكتروني المضاف غير صحيح",
      EmailIsNotVerifiedError:
        "لم يتم التحقق من بريدك الإلكتروني، لن يتم تفعيل حسابك",
      Shop: "المتجر",
      News: "الأخبار",
      Contact: "اتصل بنا",
      Setting: "الإعدادات",
      Login: "تسجيل الدخول إلى حسابك",
      Logout: "تسجيل خروج",
      Category: "التصنيف",
  
      // Checkout
      Checkout: "الدفع",
      ProceedPayment: "متابعة الدفع",
      Purchase: "شراء",
      CashOnDelivery: "الدفع عن الاستلام",
      Paypal: "باي بال",
      Stripe: "شريط",
      CreditCard: "بطاقة ائتمان",
      PaymentMethod: "طريقة الدفع - غير محدد",
      PaymentMethodError: "يرجى تحديد طريقة الدفع",
      PayWithCoD: "يرجى تحديد طريقة الدفع",
      PayWithPayPal: "الدفع بواسطة Paypal",
      PayWithStripe: "سيتم دفع الشراء مع Stripe",
      ApplyCoupon: "اضف الكوبون",
      CouponPlaceholder: "رمز الكوبون",
      APPLY: "ارسل",
      Back: "العودة",
      CardNamePlaceholder: "الاسم مكتوب على البطاقة",
      BackToHome: "العودة لرئيسة",
      OrderCompleted: "تم الانتهاء من طلبك",
      OrderCanceled: "تم إلغاء طلبك",
      OrderFailed: "تم إلغاء طلبك",
      OrderCompletedDesc: "أجل معرف الخاص بك هو ",
      OrderCanceledDesc: "تم الغاء الطلب بناء على رغبتك",
      OrderFailedDesc: "حصل خطأ ولم تكتمل عملية الشراء",
      OrderTip:
        'إضاءة: يمكنك تتبع حالة الطلب في قسم "طلباتي" من القائمة الجانبية',
      Payment: "دفع",
      Complete: "دفع...",
      EnterYourFirstName: "أدخل اسمك الأول",
      EnterYourLastName: "أدخل اسم العائلة",
      EnterYourEmail: "أدخل بريدك الإلكتروني",
      EnterYourPhone: "أدخل هاتفك",
      EnterYourAddress: "أدخل عنوانك",
      CreateOrderError: "أدخل عنوانك...",
      AccountNumner: "رقم حساب",
      CardHolderName: "إسم صاحب البطاقة",
      ExpirationDate: "تاريخ إنتهاء الصلاحية",
      SecurityCode: "CVV",
  
      // myorder
      OrderId: "رقم التعريف الخاص بالطلب",
      MyOrder: "طلبي",
      NoOrder: "لا يوجد طلبات",
      OrderDate: "تاريخ الطلب: ",
      OrderStatus: "الحالة: ",
      OrderPayment: "طريقة الدفع او السداد: ",
      OrderTotal: "مجموع: ",
      OrderDetails: "أظهر تفاصيل",
      ShippingAddress: "عنوان الشحن:",
      Refund: "إعادة مال",
  
      News: "أخبار",
      PostDetails: "قراءة المزيد",
      FeatureArticles: "مقالات",
      MostViews: "الأكثر مشاهدة",
      EditorChoice: "من اختياراتنا",
  
      // settings
      Settings: "الإعدادات",
      BASICSETTINGS: "الإعدادات الأساسية",
      Language: "اللغو",
      INFO: "معلومات",
      About: "معلومات عنا",
  
      // language
      AvailableLanguages: "اللغات المتوفرة",
      SwitchLanguage: "تبديل اللغة",
      SwitchLanguageConfirm:
        "لتبديل اللغة سوف نقوم باعادة تحميل التطبيق، هل تود المتابعة؟",
      SwitchRtlConfirm:
        "لتغيير اتجاه التطبيق سوف نقوم بإعادة تحميل التطبيق, هل تود المتابعة؟",
  
      // about us
      AppName: "MSTORE",
      AppDescription: "رد القالب الأصلي ل كومومرس",
      AppContact: " الاتصال بنا على: mstore.io",
      AppEmail: " البريد الإلكتروني: support@mstore.io",
      AppCopyRights: "© MSTORE 2016",
  
      // contact us
      contactus: "اتصل بنا",
  
      // form
      NotSelected: "فضلاً اختر",
      EmptyError: "عبئ هذ الحقل",
      DeliveryInfo: "معلومات التسليم",
      FirstName: "الاسم الاول",
      LastName: "الكنية",
      Address: "عنوان",
      City: "المدينة / المدينة",
      State: "حالة",
      NotSelectedError: "إختر واحد من فضلك",
      Postcode: "الرمز البريدي",
      Country: "بلد",
      Email: "البريد الإلكتروني",
      Phone: "رقم الهاتف",
      Note: "ملاحظة",
  
      // search
      Search: "البحث",
      SearchPlaceHolder: "البحث عن المنتج بالاسم",
      NoResultError: "نأسف، لا توجد نتائج بحث للكلمات المستخدمة",
      Details: "التفاصيل",
  
      // filter panel
      Categories: "الاقسام",
      Loading: "جار التحميل...",
      welcomeBack: "مرحبا بعودتك! ",
  
      // sign up
      profileDetail: "تفاصيل الملف الشخصي",
      firstName: "الاسم الاول",
      lastName: "الكنية",
      accountDetails: "تفاصيل الحساب",
      username: "اسم المستخدم",
      email: "البريد الإلكتروني",
      generatePass: "أنشأ لي كلمة مرور",
      password: "كلمه السر",
      signup: "سجل",
  
  
      // filter panel
      Loading: "جار التحميل...",
      welcomeBack: "مرحبا بعودتك! ",
      seeAll: "استعراض الكل",
  
      // Layout
      cardView: "بطاقة",
      simpleView: "قائمة مبسطة",
      twoColumnView: "عمودين",
      threeColumnView: "ثلاثة أعمدة",
      listView: "قائمة عمودية",
      default: "افتراضي",
      advanceView: "اسلوب متقدم",
      horizontal: "أفقي ",
  
      couponCodeIsExpired: "لم يعد هذا الكوبون صالح",
      invalidCouponCode: "هذا الكوبون غير صحيح",
      remove: "إزالة",
      applyCouponSuccess: "تهانينا! تم تطبيق الكوبون بنجاح",
      reload: "إعادة تحميل",
  
      OutOfStock: "نفذت الكمية",
      ShippingType: "طريقة الشحن",
  
      // Place holder
      TypeFirstName: "اكتب اسمك الأول",
      TypeLastName: "اكتب اسمك الأخير",
      TypeAddress: "اكتب العنوان",
      TypeState: "اكتب الولاية أو المدينة",
      TypeNotSelectedError: "إختر واحد من فضلك",
      TypePostcode: "اكتب الرمز البريدي",
      TypeEmail: "اكتب بريد الكتروني صحيح مثل email@email.com: ",
      TypePhone: "اكتب رقم هاتفك",
      TypeNote: "ملاحظة",
      TypeCountry: "حدد دولتك",
      SelectPayment: "اختار طريقة الدفع",
      close: "أغلق",
      noConnection: "لا يوجد اتصال بالإنترنت",
  
      // user profile screen
      AccountInformations: "معلومات الحساب",
      PushNotification: "التنبيهات",
      DarkTheme: "موضوع الظلام",
      Privacy: "سياسة الخصوصية",
      SelectCurrency: "اختر العملة",
      Name: "اسم",
      Gender:'جنس',
      SelectAGender:'الرجاء تحديد الجنس',
      Currency: "عملة",
      Languages: "اللغات",
  
      GetDataError: "لا يمكن الاتصال بالخادم",
      UserOrEmail: "اسم المستخدم أو البريد الالكتروني",
      Or: "أو",
      FacebookLogin: "تسجيل الدخول بواسطة الفيس بوك",
      DontHaveAccount: "لا تمتلك حساب؟",
  
      // Horizontal
      featureProducts: "منتجات مميزة",
      bagsCollections: "تشكيلة الحقائب",
      womanBestSeller: "افضل مبيعات منتجات المرأة",
      manCollections: "تشكيلة الرجل",
      jacket: 'السترة',
      hoodies: "هوديس وبلوزات",
      promotion: "الترقيات",
  
      // Modal
      Select: "تحديد",
      Cancel: "إلغاء",
      Guest: "زائر",
  
      LanguageName: "Arabic",
  
      // review
      vendorTitle: "بائع",
      comment: "ترك التعليق",
      yourcomment: "تعليقك",
      placeComment: "أخبر شيئًا عن تجربتك أو اترك نصيحة للآخرين",
      writeReview: "أكتب مراجعة",
      thanksForReview:
        "شكرًا على المراجعة ، سيتم التحقق من المحتوى الخاص بك بواسطة المشرف وسيتم نشره لاحقًا",
      errInputComment: "يرجى إدخال المحتوى الخاص بك لتقديمه",
      errRatingComment: "يرجى تصنيف لتقديم",
      send: "إرسال",
  
      termCondition: "الأحكام والشروط",
      Subtotal: "حاصل الجمع",
      Discount: "خصم",
      Shipping: "الشحن",
      Recents: "الأخيرة",
      Filters: "مرشحات",
      Princing: "التسعير",
      Filter: "منقي",
      ClearFilter: "مرشح واضح",
      ProductCatalog: "بيان المنتج",
      ProductTags: "علامات المنتج",
      AddToAddress: "أضف إلى العنوان",
      SMSLogin: "تسجيل الدخول عبر الرسائل القصيرة",
      OrderNotes: 'ترتيب ملاحظات',
      GoogleLogin: "تسجيل الدخول جوجل",
      FAQTopics: "الأسئلة الشائعة",
      FAQ: "التعليمات",
      ContactInformation: "بيانات الاتصال",
      Comment: "تعليق",
      Submit: "أرسل",
      Location: "موقعك",
      Free: "حر",
      Days: "أيام",
      NoShippingMsg: "ليس لديك أي طرق شحن لعنوانك"
    },
  };

export default new LocalizedStrings(Languages);